### ISSUE TITLE
Daemon core aborted

### ISSUE THREAD

**Issue by BKdilse** [turtlecoin/turtlecoin#199]
Running v0.4.4.1258.  Getting random aborts of the Daemon.
Last compile was a static one, and this is also causing the same issue.

I did not grab the last messages shown on the Daemon output, as this always happens at an awkward time (when I'm running late).  If it happens over the weekend, I'll grab more details.

Any suggestions on stabilising this?

**Comment by RocksteadyTC** [comment]
Need more details to know for sure what's going on. See if you can replicate with higher log level by typing `set_log #` where # denotes the numbered log level that provides the information you're looking for. Ideally we could get this replicated in the highest log level, but I understand it isn't always feasible to run a daemon with this much verbosity.

**Comment by BKdilse** [comment]
Typical, hasn't aborted.  I still can't see any logs, please confirm the location of log file, and whether the Daemon needs a restart for the log level change to take effect.

**Comment by BKdilse** [comment]
Ok thanks. I'll check it out

**Comment by SoreGums** [comment]
btw log_level 4 is the higher settings = more info

**Comment by BKdilse** [comment]
Just some more into on my setup...
I'm running the Daemon in a screen session (not as a service), not sure it that makes a difference to log creation (wouldn't have thought so).

I still don't see a log being created, looked in the directory of the daemon: `/usr/local/src/turtlecoin/build/src/`
When I so a `set_log 3` or `set_log 4`, I can see loads more output to daemon console, but again no log file.

My start up command is `/usr/local/src/turtlecoin/build/src/TurtleCoind --rpc-bind-ip 0.0.0.0`

**Comment by brandonlehmann** [comment]
Check for the log file in the directory you ran your start command from. I believe it logs to the current working directory.

**Comment by BKdilse** [comment]
@brandonlehmann nope, nothing in there either.

It's compiled using static release, btw, as this was a suggestion to resolve the abort issues.

**Comment by brandonlehmann** [comment]
Time to bust out the Linux find commands :)

**Comment by BKdilse** [comment]
Dam thing hasn't aborted, which is good, but can't get to bottom of it.  Closing for now.

**Comment by bobbieltd** [comment]
Abort logs of the Daemon (mainly because of bad peers) —> stuck/hang/out of sync ... . It often happened in the past but now it is very rare. Don’t worry too much about it. When network is stable and more nodes in sync, it won’t happen again.

**Comment by BKdilse** [comment]
This happened today:

```
2018-May-04 12:12:13.112275 INFO    Switching to alt chain! New top block: 423288 (38a44ff34ef0448676bae7919397df19a5e2f6caf1337d9332e64e2253af5305), previous top block: 423287 (f0fc314cdf20542f280718d98a279a1affa1d0ac0601dba13851dd5902837406)
2018-May-04 12:12:16.339009 INFO    New Top Block Detected: 423290
2018-May-04 12:12:30.221244 INFO    New Top Block Detected: 423291
2018-May-04 12:12:41.039717 INFO    New Top Block Detected: 423292
2018-May-04 12:12:54.639022 INFO    New Top Block Detected: 423293
2018-May-04 12:12:58.002964 INFO    New Top Block Detected: 423294
2018-May-04 12:13:17.580298 INFO    New Top Block Detected: 423295
2018-May-04 12:13:38.074683 INFO    New Top Block Detected: 423296
2018-May-04 12:14:12.302034 INFO    New Top Block Detected: 423297
2018-May-04 12:14:18.766428 INFO    New Top Block Detected: 423298
2018-May-04 12:14:42.790037 INFO    New Top Block Detected: 423299
2018-May-04 12:15:11.718228 INFO    New Top Block Detected: 423300
Segmentation fault (core dumped)
```
I'll now increase logging and see if I can capture more.

**Comment by RocksteadyTC** [comment]
This has been merged into main
@ZedPea @BKdilse

**Comment by Bathmat** [comment]
I was seeing the same issues and the fix @ZedPea posted is working well for now.

**Comment by BKdilse** [comment]
I can confirm @ZedPea fix works too.

**Comment by BKdilse** [comment]
Daemon aborted today:

2018-May-07 16:03:15.990378 INFO    New Top Block Detected: 432024
2018-May-07 16:03:56.010492 INFO    New Top Block Detected: 432025
2018-May-07 16:04:10.641565 INFO    Switching to alt chain! New top block: 432024 (08fe7d102161fc5de04848d37de2cb453c5b08e349557df55a1cee550e5ac4f5), previous top block: 432023 (3bee1663c7370e8b6a8f639ee482c949bd1f91b31f97a460f9e33892615a9adc)
2018-May-07 16:04:10.644620 INFO    New Top Block Detected: 432026
2018-May-07 16:04:20.013723 INFO    New Top Block Detected: 432027
2018-May-07 16:04:56.331988 INFO    New Top Block Detected: 432028
2018-May-07 16:05:07.627249 INFO    New Top Block Detected: 432029
2018-May-07 16:05:38.261618 INFO    New Top Block Detected: 432030
2018-May-07 16:05:50.050183 INFO    New Top Block Detected: 432031
2018-May-07 16:05:58.460872 INFO    New Top Block Detected: 432032
2018-May-07 16:06:57.698507 INFO    Switching to alt chain! New top block: 432031 (d6524c1d018e4bc330be49867ffce3e244495983660df02a5d47f12395ff5a60), previous top block: 432031 (ec5ef107d513fe77ff5f7e5c537ac06329f722b4bb376149e6aa66fd7d4b0b46)
2018-May-07 16:06:59.931626 INFO    [62.210.88.202:11897 OUT] Successfully synchronized with the TurtleCoin Network.
2018-May-07 16:07:09.826518 INFO    [114.45.161.197:11897 OUT] Successfully synchronized with the TurtleCoin Network.
2018-May-07 16:07:40.693276 INFO    New Top Block Detected: 432033
2018-May-07 16:07:45.227454 INFO    New Top Block Detected: 432034
2018-May-07 16:08:09.212953 INFO    New Top Block Detected: 432035
2018-May-07 16:08:46.581647 INFO    New Top Block Detected: 432036
TurtleCoind: /usr/local/src/turtlecoin/external/rocksdb/cache/lru_cache.cc:232: void rocksdb::LRUCacheShard::EvictFromLRU(size_t, rocksdb::autovector<rocksdb::LRUHandle*>*): Assertion `old->InCache()' failed.
Aborted (core dumped)

Is the above detail enough to diagnose this or so No need to capture more?

**Comment by brandonlehmann** [comment]
I don't think I see any notes on the system you're running it on. Do you mind sharing some details?

Distro:
Distro Version:
GCC Version:
CPU Type & Model #:
How much RAM:
Free Disk Space:

**Comment by BKdilse** [comment]
Sure:

```
Distro: Ubuntu Ubuntu
Distro Version: 16.04.4 LTS
GCC Version: 5.4.0 20160609
CPU Type & Model #: Intel(R) Xeon(R) CPU E3-1225 v3 @ 3.20GHz
How much RAM: 5GB
Free Disk Space: 76GB
```

I'm running this as a Virtual Machine on VMware ESXi 6.5, along with another 9 coin pools.  Each built in a similar way, with similar specs.

**Comment by brandonlehmann** [comment]
Got it. Thanks!

When was the last time you did a full rebuild of your local copy of the chain?

**Comment by BKdilse** [comment]
Can't be sure, I thought I did it yesterday, timestamp on ~/.TurtleCoin is 06/05/2018, oldest file within DB directory is 08/04/2018.  Is there a way to find out (sorry had a lot on yesterday, brain not fully functioning).

**Comment by brandonlehmann** [comment]
If the oldest file in the DB folder is from April, it looks like it’s been a while. 

For good measure, I would nuke the folder and bootstrap it to be safe.

**Comment by BKdilse** [comment]
OK I'll give that a go now.  Is there a preferred method for this?
I normally stop the Daemon & Wallet, delete the ~/.TurtleCoin folder, and then start the Daemon.

**Comment by brandonlehmann** [comment]
That’ll work. If you take a look at https://github.com/turtlecoin/turtlecoin/wiki/Bootstrapping-the-Blockchain you can bootstrap and speed that resync up quite a bit.

**Comment by BKdilse** [comment]
thanks, I'll give that a go.

**Comment by BKdilse** [comment]
Bootstrap down and sync complete.  I'll monitor it now. Thanks

**Comment by Bathmat** [comment]
I'm starting to see a lot of this again today... I did a full resync of the blockchain yesterday too....

**Comment by BKdilse** [comment]
My pools been down all day. Got aborts multiple times, a few seconds after starting daemon.  I started it 6 times in a row,n within 3-4 mins.  Worked for a bit then aborted again. This time saw corrupt blockchain messages, so wiped clean and done bootstrap again.  Can't go on like this, so would appreciate next steps in troubleshooting this please.

**Comment by Bathmat** [comment]
I've tried multiple versions of the Daemon/wallet 4.2, 4.3, 4.4 and compile from latest code....

**Comment by RocksteadyTC** [comment]
There's a known issue that we've pushed a consensus upgrade for. Every time someone broadcasts a transaction with a lot of inputs and a ridiculous high mixin, mac and linux daemons segfault or exhibit other weird behavior.

**Comment by cryptonote-social** [comment]
Can't keep the Daemin running for more than a few minutes tops today. And this is after a full sync since last night my blockchain became corrupted. I'm also running on Ubuntu 16.04.

**Comment by RocksteadyTC** [comment]
We are currently under attack. The latest PR merges limiting ridiculous mixins addresses this.

**Comment by Bathmat** [comment]
I just don't understand why people gotta be jerks like that....

**Comment by cryptonote-social** [comment]
I've built to head with all the most recent changes and still seeing regular crashes, in case that's of any help.

**Comment by RocksteadyTC** [comment]
https://medium.com/@turtlecoin/were-under-attack-here-s-what-s-happening-and-how-you-can-help-f359eb73496f

**Comment by BKdilse** [comment]
Thanks guys, Daemon now updated, and pool working.  I'll monitor and provide feedback.

**Comment by ereptor81** [comment]
It still has the potential to crash, even on 0.5 until 1) the network has consensus on 0.5 and 2) your local chain clears past the consensus point. Until that happens you'll just have to keep restarting the daemon. You shouldn't need to resync unless the chain corrupts.

**Comment by cryptonote-social** [comment]
Installed & running.  Interestingly I had no crashes last night even before the upgrade.

**Comment by cryptonote-social** [comment]
...aaand we are now past block 440K!

**Comment by BKdilse** [comment]
Dam, already deleted and started synching. Oh well. Thanks for the clarification though.

**Comment by bobbieltd** [comment]
+1 it seems nodejs-pool pool owners are very active 👍👍👍 with issues. For info, I had troubles with daemon because of attacks too.

**Comment by BKdilse** [comment]
Daem9n now past 44000, and looking good.

**Comment by cryptonote-social** [comment]
Sadly I just had my first daemon abort since the update.  Anything details I can provide to help debug things when this happens?  The LOG doesn't seem to contain a whole lot of info.

**Comment by BKdilse** [comment]
Mine has been fine luckily.  I report back any issues if they occur.

**Comment by cryptonote-social** [comment]
Didn't crash but found it locked up and not responding this morning :/  Had to restart.  Let me know if there's some kind of logging I can enable to help get to the bottom of this.

**Comment by BKdilse** [comment]
Segmentation fault (core dumped) started again:

2018-May-18 23:48:48.781700 INFO    New Top Block Detected: 463345

will increase logging

**Comment by darutse** [comment]
same thing but at Block 436800.. can't sync...

**Comment by ZedPea** [comment]
If you're getting segfaults between 430k and 440k you just need to restart to get past them, should be fine after that.
